# Generated by Django 3.0.4 on 2020-03-15 20:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_trashcollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='trashcollection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trashcollection',
            name='verified_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trashcollection',
            name='verified',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
