# Generated by Django 3.0.4 on 2020-03-15 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200315_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trashcollection',
            name='verified_at',
        ),
    ]
