# Generated by Django 3.0.4 on 2020-03-15 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_trashcollection_verified_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trashcollection',
            old_name='created_at',
            new_name='uploaded_at',
        ),
    ]
