# Generated by Django 3.0.4 on 2020-03-15 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200315_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trashcollection',
            name='verified',
            field=models.BooleanField(null=True),
        ),
    ]
