# Generated by Django 3.0.4 on 2020-03-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200315_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trashcollection',
            name='verified',
            field=models.NullBooleanField(),
        ),
    ]
