# Generated by Django 3.0.4 on 2020-03-18 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200316_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='trashcollection',
            name='photo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Photo'),
        ),
    ]
