# Generated by Django 3.0.4 on 2020-07-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20200407_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='trashcollection',
            name='downvotes',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='trashcollection',
            name='upvotes',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
