# Generated by Django 3.0.4 on 2020-07-18 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20200716_1940'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='activity',
            unique_together={('user', 'photo')},
        ),
    ]
