# Generated by Django 3.0.4 on 2020-07-20 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20200718_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='collections',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='posts',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verifications',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
