# Generated by Django 3.0.4 on 2020-07-21 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20200720_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrashCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('upvotes', models.IntegerField(blank=True, default=0)),
                ('downvotes', models.IntegerField(blank=True, default=0)),
                ('rejected', models.BooleanField(default=False)),
                ('collector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poster', to=settings.AUTH_USER_MODEL)),
                ('photo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Photo')),
            ],
        ),
    ]
