# Generated by Django 3.0.4 on 2020-07-21 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_trashcollection'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrashCollectionActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('vote', models.IntegerField(default=0)),
                ('trash_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trash_collection_activity_trash_collection', to='api.TrashCollection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trash_collection_activity_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'trash_collection')},
            },
        ),
    ]
