# Generated by Django 3.0.4 on 2020-07-22 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_trashcollectionactivity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trashcollection',
            old_name='rejected',
            new_name='visible',
        ),
    ]
