# Generated by Django 3.0.4 on 2020-07-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20200722_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='trashcollection',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
