# Generated by Django 3.0.4 on 2020-07-29 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20200725_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=16, default=0, max_digits=22),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=16, default=0, max_digits=22),
            preserve_default=False,
        ),
    ]
