# Generated by Django 3.0.4 on 2020-08-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_photo_indoors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='indoors',
        ),
        migrations.AddField(
            model_name='photo',
            name='is_indoors',
            field=models.BooleanField(default=False),
        ),
    ]
