# Generated by Django 3.0.4 on 2020-08-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20200801_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='scale',
            field=models.IntegerField(default=2),
        ),
    ]
